name: Build Docker Image

on:
  workflow_dispatch:

env:
  TEST_TAG: yyovkov/hf-ter:test

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        timeout-minutes: 1

      - name: Set up Docker Buildx
        timeout-minutes: 1
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and export to Docker
        timeout-minutes: 15
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          context: .
          load: true
          tags: test

      - name: Test
        run: |
          docker run --rm test

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: yyovkov/hf-ter:latest

